[package]
name = "kfly"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "3.1.1"
dialoguer = "0.12.0"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
textwrap = "0.16.2"
toml = "1.0.3"
